# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Practice0719' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Practice0719
  pod 'RealmSwift', '10.33.0'
  target 'Practice0719Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Practice0719UITests' do
    # Pods for testing
  end

end
